# Generated by Django 4.1.5 on 2023-07-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dateCreate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
