# Generated by Django 4.1.5 on 2023-07-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_comment_datecreate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentRating',
            field=models.IntegerField(default=0),
        ),
    ]
